# Generated by Django 4.0.5 on 2022-06-27 16:22

import data.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='profile',
            name='gander',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('famale', 'famale')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.upload_to),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_name',
            field=models.CharField(blank=True, choices=[('doctor', 'doctor'), ('patient', 'patient')], max_length=50, null=True),
        ),
    ]
