# Generated by Django 4.0.5 on 2022-06-27 23:37

import data.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_profile_options_profile_gander_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronic_diseases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('diseases_name', models.CharField(blank=True, choices=[('التهاب المفاصل', 'التهاب المفاصل'), ('أمراض القلب و الأوعية الدموية', 'أمراض القلب و الأوعية الدموية'), ('أمراض الجهاز التنفسي', 'أمراض الجهاز التنفسي'), ('السرطان', 'السرطان'), ('السكري', 'السكري'), ('الصرع والنوبات', 'الصرع والنوبات'), ('السمنة', 'السمنة'), ('مشاكل صحة الفم', 'مشاكل صحة الفم'), ('مرض الكلى المزمن (الفشل الكلوي)', 'مرض الكلى المزمن (الفشل الكلوي)'), ('قصور الغدة الدرقية', 'قصور الغدة الدرقية'), ('أمراض الجهاز الهضمي', 'أمراض الجهاز الهضمي'), ('ارتفاع الدهنيات', 'ارتفاع الدهنيات'), ('مرض سيولة الدم', 'مرض سيولة الدم')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.profile')),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=200, null=True)),
                ('identification', models.ImageField(blank=True, null=True, upload_to=data.models.upload_to)),
                ('social_website', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('data.profile',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.profile')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('patientDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patient_set', to='data.doctor')),
            ],
            bases=('data.profile',),
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_arabic', models.CharField(max_length=50, verbose_name='governorate_name_ar')),
                ('state_english', models.CharField(max_length=50, verbose_name='governorate_name_en')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_chronic_diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='data.chronic_diseases')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='data.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ChestDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('regestration_date', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_x_ray', to='data.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_comment', models.TextField(blank=True, null=True)),
                ('evaluation', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='data.doctor')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='data.patient')),
            ],
            options={
                'unique_together': {('owner', 'doctor')},
            },
        ),
    ]
