# Generated by Django 4.0.5 on 2022-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Giza', 'Giza'), ('Shubra', 'Shubra El Kheima'), ('Port_Said', 'Port Said'), ('Suez', 'Suez'), ('Mahalla', 'Mahalla (Gharbia)'), ('Luxor', 'Luxor'), ('Mansoura', 'Mansoura (Dakahlia)'), ('Tanta', 'Tanta (Gharbia)'), ('Asyut', 'Asyut'), ('Ismailia', 'Ismailia'), ('Faiyum', 'Faiyum'), ('Zagazig', 'Zagazig (Sharqia)'), ('Damietta', 'Damietta'), ('Aswan', 'Aswan'), ('Minya', 'Minya'), ('Damanhur', 'Damanhur (Beheira)'), ('Beni_Suef', 'Beni Suef'), ('Hurghada', 'Hurghada (Red Sea)'), ('Qena', 'Qena'), ('Sohag', 'Sohag'), ('Shibin', 'Shibin El Kom (Monufia)'), ('Banha', 'Banha (Qalyubia)'), ('Arish', 'Arish (North Sinai)')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='state',
        ),
    ]
