# Generated by Django 4.0.5 on 2022-07-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_profile_city_id_profile_city_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='governorates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('governorate_name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('governorate_name_en', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('city_name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('city_name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('governorate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='data.governorates')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.cities'),
        ),
    ]
