# Generated by Django 4.0.5 on 2022-07-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_governorates_remove_profile_city_cities_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cities',
            new_name='citiess',
        ),
    ]
