# Generated by Django 4.0.5 on 2022-07-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_profile_city_id_delete_citiess'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('city_name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('governorate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='data.governorates')),
            ],
        ),
    ]
