# Generated by Django 4.0.5 on 2022-07-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='governorate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.governorates'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Specialization', to='data.specialization'),
        ),
    ]
