# Generated by Django 4.0.5 on 2022-07-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_specialization_profile_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='Specialization_name',
            field=models.CharField(blank=True, choices=[('Chest doctor', 'Chest doctor'), ('Internist', 'Internist'), ('Anesthetist', 'Anesthetist')], max_length=50, null=True),
        ),
    ]
